name: Docker Build and Trivy Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t vamshi/hello-app .

    - name: Install Trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: image
        image-ref: vamshi/hello-app
